// <auto-generated />
using System;
using CoreApp.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreApp.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190113065422_FixedPaymentData")]
    partial class FixedPaymentData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoreApp.Models.Repositories.CountryDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("VinPrefix");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F160", Name = "South Africa", VinPrefix = "BA-BE" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F161", Name = "Angola", VinPrefix = "BA-BE" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F162", Name = "Kenya", VinPrefix = "BF-BK" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F163", Name = "Tanzania", VinPrefix = "BL-BR" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F165", Name = "Benin", VinPrefix = "CA-CE" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F166", Name = "Madagascar", VinPrefix = "CF-CK" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F167", Name = "Tunisia", VinPrefix = "CL-CR" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F169", Name = "Egypt", VinPrefix = "DA-DE" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F110", Name = "Morocco", VinPrefix = "DF-DK" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-1188C7F3F520", Name = "Zambia", VinPrefix = "DL-DR" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F540", Name = "Ethiopia", VinPrefix = "EA-EE" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F550", Name = "Mozambique", VinPrefix = "EF-EK" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F508", Name = "Ghana", VinPrefix = "FA-FE" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F507", Name = "Nigeria", VinPrefix = "FF-FK" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F503", Name = "Japan", VinPrefix = "J" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F502", Name = "Sri Lanka", VinPrefix = "KA-KE" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F501", Name = "Israel", VinPrefix = "KF-KK" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F565", Name = "Korea (South)", VinPrefix = "KL-KR" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F516", Name = "Kazakhstan", VinPrefix = "KS-K0" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", Name = "China (Mainland)", VinPrefix = "L" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F518", Name = "India", VinPrefix = "MA-ME" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F519", Name = "Indonesia", VinPrefix = "MF-MK" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F520", Name = "Thailand", VinPrefix = "ML-MR" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F521", Name = "Myanmar", VinPrefix = "MS-M0" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F522", Name = "Iran", VinPrefix = "NA-NE" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F523", Name = "Pakistan", VinPrefix = "NF-NK" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F524", Name = "Turkey", VinPrefix = "NL-NR" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F526", Name = "Philippines", VinPrefix = "PA-PE" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F527", Name = "Singapore", VinPrefix = "PF-PK" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F528", Name = "Malaysia", VinPrefix = "PL-PR" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F530", Name = "United Arab Emirates", VinPrefix = "RA-RE" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F531", Name = "Taiwan", VinPrefix = "RF-RK" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F532", Name = "Vietnam", VinPrefix = "RL-RR" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F533", Name = "Saudi Arabia", VinPrefix = "RS-R0" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F534", Name = "United Kingdom", VinPrefix = "SA-SM" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F535", Name = "Germany (formerly East Germany)", VinPrefix = "SN-ST" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F536", Name = "Poland", VinPrefix = "SU-SZ" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F537", Name = "Latvia", VinPrefix = "S1-S4" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F539", Name = "Switzerland", VinPrefix = "TA-TH" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F540", Name = "Czech Republic", VinPrefix = "TJ-TP" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F541", Name = "Hungary", VinPrefix = "TR-TV" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F542", Name = "Portugal", VinPrefix = "TW-T1" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F545", Name = "Denmark", VinPrefix = "UH-UM" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F546", Name = "Ireland", VinPrefix = "UN-UT" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F547", Name = "Romania", VinPrefix = "UU-UZ" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F549", Name = "Slovakia", VinPrefix = "U5-U7" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F551", Name = "Austria", VinPrefix = "VA-VE" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F552", Name = "France", VinPrefix = "VF-VR" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F553", Name = "Spain", VinPrefix = "VS-VW" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F554", Name = "Serbia", VinPrefix = "VX-V2" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F555", Name = "Croatia", VinPrefix = "V3-V5" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F556", Name = "Estonia", VinPrefix = "V6-V0" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", Name = "Germany (formerly West Germany)", VinPrefix = "W" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F558", Name = "Bulgaria", VinPrefix = "XA-XE" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F559", Name = "Greece", VinPrefix = "XF-XK" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F561", Name = "Netherlands", VinPrefix = "XL-XR" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F562", Name = "Russia (former USSR)", VinPrefix = "XS-XW" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F563", Name = "Luxembourg", VinPrefix = "XX-X2" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F564", Name = "Russia", VinPrefix = "X3-X0" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F565", Name = "Belgium", VinPrefix = "YA-YE" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F566", Name = "Finland", VinPrefix = "YF-YK" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F567", Name = "Malta", VinPrefix = "YL-YR" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F568", Name = "Sweden", VinPrefix = "YS-YW" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F569", Name = "Norway", VinPrefix = "YX-Y2" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F570", Name = "Belarus", VinPrefix = "Y3-Y5" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F571", Name = "Ukraine", VinPrefix = "Y6-Y0" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F572", Name = "Italy", VinPrefix = "ZA-ZR" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F574", Name = "Slovenia", VinPrefix = "ZX-Z2" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F575", Name = "Lithuania", VinPrefix = "Z3-Z5" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", Name = "United States", VinPrefix = "5" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F580", Name = "Canada", VinPrefix = "2" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F581", Name = "Mexico", VinPrefix = "3A-3W" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F582", Name = "Costa Rica", VinPrefix = "3X-37" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F583", Name = "Cayman Islands", VinPrefix = "38-39" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F585", Name = "Australia", VinPrefix = "6" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F586", Name = "New Zealand", VinPrefix = "7" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F587", Name = "Argentina", VinPrefix = "8A-8E" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F588", Name = "Chile", VinPrefix = "8F-8K" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F589", Name = "Ecuador", VinPrefix = "8L-8R" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F590", Name = "Peru", VinPrefix = "8S-8W" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F591", Name = "Venezuela", VinPrefix = "8X-82" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F593", Name = "Brazil", VinPrefix = "9A-9E" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F594", Name = "Colombia", VinPrefix = "9F-9K" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F595", Name = "Paraguay", VinPrefix = "9L-9R" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F596", Name = "Uruguay", VinPrefix = "9S-9W" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F597", Name = "Trinidad & Tobago", VinPrefix = "9X-92" },
                        new { Id = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", Name = "Brazil", VinPrefix = "93–99" }
                    );
                });

            modelBuilder.Entity("CoreApp.Models.Repositories.FileDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Filename");

                    b.Property<int>("Length");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("CoreApp.Models.Repositories.FilePieceDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Hash");

                    b.Property<int>("Length");

                    b.HasKey("Id");

                    b.ToTable("Piece");
                });

            modelBuilder.Entity("CoreApp.Models.Repositories.FilePiecesDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FileId");

                    b.Property<string>("FilePieceId");

                    b.Property<int>("PieceNumber");

                    b.HasKey("Id");

                    b.ToTable("FilePieces");
                });

            modelBuilder.Entity("CoreApp.Models.Repositories.PasswordDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateSet");

                    b.Property<string>("Hash");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Passwords");
                });

            modelBuilder.Entity("CoreApp.Models.Repositories.PostDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PostTypeId");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("CoreApp.Models.Repositories.PostTypeDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("PostTypes");
                });

            modelBuilder.Entity("CoreApp.Models.Repositories.SessionDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("SetTime");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("CoreApp.Models.Repositories.UserDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmailAddress");

                    b.Property<string>("ImageId");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CoreApp.Models.Repositories.Vehicle.CarDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ManufacturerId");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CoreApp.Models.Repositories.Vehicle.ManufacturerDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("VinPrefix");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0024", Name = "Toyota" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0025", Name = "KIA" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0026", Name = "Ford" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0027", Name = "Hyundai" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0028", Name = "Proton" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0029", Name = "Smart" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0030", Name = "Audi" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0031", Name = "Suzuki" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0032", Name = "Dacia" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0033", Name = "ÖAF" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0034", Name = "Honda" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0035", Name = "Nissan" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0036", Name = "Škoda" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0037", Name = "SEAT" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0038", Name = "Tauro Sport Auto" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0039", Name = "Chevrolet" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0040", Name = "Mitsubishi" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0041", Name = "General Motors" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0042", Name = "Saab" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0043", Name = "Acura" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0044", Name = "Volkswagen" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0045", Name = "DAF Trucks" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0046", Name = "Ontario Drive & Gear" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0047", Name = "Pontiac" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0048", Name = "Gnome Homes" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0049", Name = "Les Contenants Durabac" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0050", Name = "Mercury" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0051", Name = "Holden" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0052", Name = "Japanese Import" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0053", Name = "NZ Transport Agency" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0054", Name = "Fiat" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0055", Name = "Renault" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0056", Name = "Mercedes Benz" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0057", Name = "Citroën" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0058", Name = "Peugeot" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0059", Name = "Iveco" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0060", Name = "Chery" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0061", Name = "Lifan" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0062", Name = "Mazda" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0063", Name = "Volkswagen Commercial Vehicles" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0064", Name = "Isuzu" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0065", Name = "IvecoBus" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0066", Name = "Geely" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0067", Name = "DaimlerChrysler AG/Daimler AG" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0068", Name = "Alexander Dennis" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0069", Name = "Bugatti" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0070", Name = "Maserati" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0071", Name = "Alfa Romeo" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0072", Name = "Ferrari" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0073", Name = "Lamborghini" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0074", Name = "Lancia" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0075", Name = "Dodge" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0076", Name = "Wallyscar" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0077", Name = "Fuji Heavy Industries" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0078", Name = "Yamaha" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0079", Name = "Daewoo" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0080", Name = "SsangYong" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0081", Name = "BMW" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0082", Name = "Hyundai" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0083", Name = "Subaru" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0084", Name = "Volvo" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0085", Name = "Jaguar" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0086", Name = "Land Rover" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0087", Name = "Rover" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0088", Name = "Triumph" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0089", Name = "Mclaren" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0090", Name = "Lotus" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0091", Name = "Aston Martin" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0092", Name = "DeLorean" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0093", Name = "Google" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0094", Name = "Scania" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0095", Name = "Opel" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0096", Name = "DS Automobiles" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0097", Name = "Talbot" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0098", Name = "Neoplan" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0099", Name = "Alpina" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0100", Name = "Porsche" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0101", Name = "Quattro" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0102", Name = "RUF" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0103", Name = "MAN" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0104", Name = "Karl Kässbohrer Fahrzeugwerke" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0105", Name = "Jeep" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0106", Name = "EvoBus" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0107", Name = "Irmscher" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0108", Name = "Mini" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0109", Name = "Chrysler" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0110", Name = "Oldsmobile" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0111", Name = "Lincon" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0112", Name = "Continental" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0113", Name = "Tesla" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0114", Name = "Jaguar" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0115", Name = "King Long" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0116", Name = "FAW Car" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0117", Name = "BYD" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0118", Name = "Yutong" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0119", Name = "Dongfeng Fengshen" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0120", Name = "Great Wall" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0121", Name = "FAW Haima" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0122", Name = "JAC" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0123", Name = "GAC Trumpchi" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0124", Name = "SAIC Maxus" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0125", Name = "SAIC GM Wuling" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0126", Name = "SAIC MG" },
                        new { Id = "8b6e9487-db5b-4985-9852-ecca594d0127", Name = "SAIC General Motors" }
                    );
                });

            modelBuilder.Entity("CoreApp.Models.Repositories.Vehicle.MileageRecordingDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Mileage");

                    b.Property<string>("OwnedCarId");

                    b.Property<DateTime>("RecordingDate");

                    b.HasKey("Id");

                    b.HasIndex("OwnedCarId");

                    b.ToTable("MileageRecordings");
                });

            modelBuilder.Entity("CoreApp.Models.Repositories.Vehicle.OwnedCarDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CarId");

                    b.Property<DateTime>("ManufacturedDate");

                    b.Property<string>("Nickname");

                    b.Property<string>("UserId");

                    b.Property<string>("Vin");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("OwnedCars");
                });

            modelBuilder.Entity("CoreApp.Models.Repositories.Vehicle.VinVDS", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Matcher");

                    b.HasKey("Id");

                    b.ToTable("VinVDSs");
                });

            modelBuilder.Entity("CoreApp.Models.Repositories.Vehicle.VinVIS", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Matcher");

                    b.HasKey("Id");

                    b.ToTable("VinVISs");
                });

            modelBuilder.Entity("CoreApp.Models.Repositories.Vehicle.VinWMI", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CountryId");

                    b.Property<string>("ManufacturerId");

                    b.Property<string>("Matcher");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("VinWMIs");

                    b.HasData(
                        new { Id = "1", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0127", Matcher = "LSG" },
                        new { Id = "2", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0126", Matcher = "LSJ" },
                        new { Id = "3", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0024", Matcher = "LTV" },
                        new { Id = "4", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0024", Matcher = "LVG" },
                        new { Id = "5", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0062", Matcher = "LVR" },
                        new { Id = "6", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0026", Matcher = "LVS" },
                        new { Id = "7", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0054", Matcher = "LWV" },
                        new { Id = "8", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0125", Matcher = "LZW" },
                        new { Id = "9", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0121", Matcher = "LH1" },
                        new { Id = "10", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0122", Matcher = "LJ1" },
                        new { Id = "11", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0123", Matcher = "LMG" },
                        new { Id = "12", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0124", Matcher = "LSFA" },
                        new { Id = "13", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0044", Matcher = "LFV" },
                        new { Id = "14", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0035", Matcher = "LGB" },
                        new { Id = "15", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0119", Matcher = "LGJ" },
                        new { Id = "16", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0120", Matcher = "LGW" },
                        new { Id = "17", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0025", Matcher = "LJD" },
                        new { Id = "18", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0096", Matcher = "LPA" },
                        new { Id = "19", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0031", Matcher = "LS5" },
                        new { Id = "20", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0044", Matcher = "LSV" },
                        new { Id = "21", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0117", Matcher = "LC0" },
                        new { Id = "22", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0058", Matcher = "LDC" },
                        new { Id = "23", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0056", Matcher = "LE4" },
                        new { Id = "24", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0024", Matcher = "LFM" },
                        new { Id = "25", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0116", Matcher = "LFP" },
                        new { Id = "26", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0117", Matcher = "LGX" },
                        new { Id = "27", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0034", Matcher = "LHG" },
                        new { Id = "28", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0034", Matcher = "LVH" },
                        new { Id = "29", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0118", Matcher = "LZY" },
                        new { Id = "30", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F521", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0025", Matcher = "MS0" },
                        new { Id = "31", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F524", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0024", Matcher = "NMT" },
                        new { Id = "32", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F524", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0026", Matcher = "NM0" },
                        new { Id = "33", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F528", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0028", Matcher = "PL1" },
                        new { Id = "34", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F539", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0029", Matcher = "TCC" },
                        new { Id = "35", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F541", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0030", Matcher = "TRU" },
                        new { Id = "36", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F541", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0031", Matcher = "TSM" },
                        new { Id = "37", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F549", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0025", Matcher = "U5Y" },
                        new { Id = "38", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F547", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0032", Matcher = "UU" },
                        new { Id = "39", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F551", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0033", Matcher = "VA0" },
                        new { Id = "40", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F540", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0026", Matcher = "TMA" },
                        new { Id = "41", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F580", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0026", Matcher = "2F" },
                        new { Id = "42", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F580", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0026", Matcher = "2HM" },
                        new { Id = "43", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F580", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0024", Matcher = "2T" },
                        new { Id = "44", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F581", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0026", Matcher = "3F" },
                        new { Id = "45", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F581", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0025", Matcher = "3KP" },
                        new { Id = "46", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F585", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0026", Matcher = "6F" },
                        new { Id = "47", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F585", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0024", Matcher = "6T1" },
                        new { Id = "48", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F580", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0034", Matcher = "2HG" },
                        new { Id = "49", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F580", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0034", Matcher = "2HJ" },
                        new { Id = "50", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F580", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0034", Matcher = "2HK" },
                        new { Id = "51", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F581", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0034", Matcher = "3HG" },
                        new { Id = "52", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F581", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0034", Matcher = "3HM" },
                        new { Id = "53", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F581", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0035", Matcher = "3N" },
                        new { Id = "54", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F586", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0034", Matcher = "7A3" },
                        new { Id = "55", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F586", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0024", Matcher = "7A4" },
                        new { Id = "56", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F586", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0026", Matcher = "7A5" },
                        new { Id = "57", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F587", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0026", Matcher = "8AF" },
                        new { Id = "58", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F587", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0024", Matcher = "8AJ" },
                        new { Id = "59", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F587", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0034", Matcher = "8C3" },
                        new { Id = "60", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F596", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0025", Matcher = "9UW" },
                        new { Id = "61", CountryId = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F160", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0024", Matcher = "AHT" },
                        new { Id = "62", CountryId = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F160", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0026", Matcher = "AFA" },
                        new { Id = "63", CountryId = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F503", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0034", Matcher = "JHL" },
                        new { Id = "64", CountryId = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F503", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0034", Matcher = "JHM" },
                        new { Id = "65", CountryId = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F503", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0035", Matcher = "JN" },
                        new { Id = "66", CountryId = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F503", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0031", Matcher = "JS" },
                        new { Id = "67", CountryId = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F503", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0024", Matcher = "JT" },
                        new { Id = "68", CountryId = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F565", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0026", Matcher = "KMH" },
                        new { Id = "69", CountryId = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F565", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0025", Matcher = "KN" },
                        new { Id = "70", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F534", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0024", Matcher = "SB1" },
                        new { Id = "71", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F534", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0034", Matcher = "SHH" },
                        new { Id = "72", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F534", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0034", Matcher = "SHS" },
                        new { Id = "73", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F534", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0035", Matcher = "SJN" },
                        new { Id = "74", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F552", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0024", Matcher = "VNK" },
                        new { Id = "75", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0030", Matcher = "WAU" },
                        new { Id = "76", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0026", Matcher = "WF0" },
                        new { Id = "77", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0026", Matcher = "1F" },
                        new { Id = "78", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0034", Matcher = "1HG" },
                        new { Id = "79", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0035", Matcher = "1N" },
                        new { Id = "80", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0026", Matcher = "1ZV" },
                        new { Id = "81", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0034", Matcher = "4S6" },
                        new { Id = "82", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0024", Matcher = "4T" },
                        new { Id = "83", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0034", Matcher = "5FN" },
                        new { Id = "84", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0034", Matcher = "5J6" },
                        new { Id = "85", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0035", Matcher = "5N1" },
                        new { Id = "86", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0026", Matcher = "5NM" },
                        new { Id = "87", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0026", Matcher = "5NP" },
                        new { Id = "88", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0024", Matcher = "5T" },
                        new { Id = "89", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0026", Matcher = "9BF" },
                        new { Id = "90", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0034", Matcher = "93H" },
                        new { Id = "91", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0024", Matcher = "9BR" },
                        new { Id = "92", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0035", Matcher = "94D" },
                        new { Id = "93", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0030", Matcher = "99A" },
                        new { Id = "94", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0034", Matcher = "9C2" },
                        new { Id = "95", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0031", Matcher = "9CD" },
                        new { Id = "96", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F540", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0036", Matcher = "TMB" },
                        new { Id = "97", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F553", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0037", Matcher = "VSS" },
                        new { Id = "98", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F553", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0038", Matcher = "VV9" },
                        new { Id = "99", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F561", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0045", Matcher = "XLR" },
                        new { Id = "101", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F566", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0042", Matcher = "YK1" },
                        new { Id = "102", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F580", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0046", Matcher = "2DG" },
                        new { Id = "103", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F580", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0041", Matcher = "2Gx" },
                        new { Id = "104", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F580", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0039", Matcher = "2G1" },
                        new { Id = "105", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F580", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0047", Matcher = "2G2" },
                        new { Id = "106", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F580", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0048", Matcher = "2G9" },
                        new { Id = "107", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F580", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0043", Matcher = "2HH" },
                        new { Id = "108", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F580", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0049", Matcher = "2L9" },
                        new { Id = "109", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F580", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0050", Matcher = "2M" },
                        new { Id = "110", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F581", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0041", Matcher = "3G" },
                        new { Id = "111", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F581", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0044", Matcher = "3VW" },
                        new { Id = "112", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F585", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0041", Matcher = "6G" },
                        new { Id = "113", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F585", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0039", Matcher = "6G1" },
                        new { Id = "114", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F585", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0047", Matcher = "6G2" },
                        new { Id = "115", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0044", Matcher = "WVG" },
                        new { Id = "116", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0044", Matcher = "WVW" },
                        new { Id = "117", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F568", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0042", Matcher = "YS3" },
                        new { Id = "118", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0041", Matcher = "1G" },
                        new { Id = "119", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0039", Matcher = "1G1" },
                        new { Id = "120", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0039", Matcher = "1GC" },
                        new { Id = "121", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0047", Matcher = "1GM" },
                        new { Id = "122", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0044", Matcher = "1VW" },
                        new { Id = "123", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0041", Matcher = "9BG" },
                        new { Id = "124", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0044", Matcher = "9BW" },
                        new { Id = "125", CountryId = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F503", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0040", Matcher = "JMB" },
                        new { Id = "126", CountryId = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F160", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0044", Matcher = "AAV" },
                        new { Id = "127", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F520", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0040", Matcher = "MMB" },
                        new { Id = "128", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F587", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0041", Matcher = "8AG" },
                        new { Id = "129", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F587", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0044", Matcher = "8AW" },
                        new { Id = "130", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F586", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0040", Matcher = "7A1" },
                        new { Id = "131", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F585", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0040", Matcher = "6MM" },
                        new { Id = "132", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F585", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0051", Matcher = "6H" },
                        new { Id = "133", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F585", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0052", Matcher = "6U9" },
                        new { Id = "134", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F586", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0053", Matcher = "7A8" },
                        new { Id = "135", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F586", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0053", Matcher = "7AT" },
                        new { Id = "136", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F587", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0054", Matcher = "8AP" },
                        new { Id = "137", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F587", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0055", Matcher = "8A1" },
                        new { Id = "138", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F587", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0056", Matcher = "8AC" },
                        new { Id = "139", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F587", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0057", Matcher = "8BC" },
                        new { Id = "140", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F587", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0058", Matcher = "8AD" },
                        new { Id = "141", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F587", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0059", Matcher = "8AT" },
                        new { Id = "142", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F596", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0060", Matcher = "9UJ" },
                        new { Id = "143", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F596", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0061", Matcher = "9UK" },
                        new { Id = "144", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F520", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0062", Matcher = "MM0" },
                        new { Id = "145", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F572", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0059", Matcher = "ZCF" },
                        new { Id = "146", CountryId = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F503", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0062", Matcher = "JM6" },
                        new { Id = "147", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0061", Matcher = "LLV" },
                        new { Id = "148", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0060", Matcher = "LVV" },
                        new { Id = "149", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F552", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0055", Matcher = "VF1" },
                        new { Id = "150", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F552", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0055", Matcher = "VF2" },
                        new { Id = "151", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F552", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0058", Matcher = "VF3" },
                        new { Id = "152", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F552", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0057", Matcher = "VF7" },
                        new { Id = "153", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0059", Matcher = "WJM" },
                        new { Id = "154", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0062", Matcher = "1YV" },
                        new { Id = "155", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0062", Matcher = "4F" },
                        new { Id = "156", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0058", Matcher = "936" },
                        new { Id = "157", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0057", Matcher = "935" },
                        new { Id = "158", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0055", Matcher = "93Y" },
                        new { Id = "159", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0060", Matcher = "98R" },
                        new { Id = "160", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0056", Matcher = "9BM" },
                        new { Id = "161", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0059", Matcher = "93Z" },
                        new { Id = "162", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F572", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0065", Matcher = "ZGA" },
                        new { Id = "163", CountryId = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F503", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0064", Matcher = "JA" },
                        new { Id = "164", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0066", Matcher = "L6T" },
                        new { Id = "165", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0066", Matcher = "LB3" },
                        new { Id = "166", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F534", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0068", Matcher = "SFD" },
                        new { Id = "167", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F534", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0068", Matcher = "SFE" },
                        new { Id = "168", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F552", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0065", Matcher = "VFE" },
                        new { Id = "169", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0067", Matcher = "WDC" },
                        new { Id = "170", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0067", Matcher = "WDD" },
                        new { Id = "171", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0067", Matcher = "WMX" },
                        new { Id = "172", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0063", Matcher = "WV1" },
                        new { Id = "173", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0063", Matcher = "WV2" },
                        new { Id = "174", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F572", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0069", Matcher = "ZA9" },
                        new { Id = "175", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F572", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0070", Matcher = "ZAM" },
                        new { Id = "176", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F572", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0071", Matcher = "ZAR" },
                        new { Id = "177", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F572", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0054", Matcher = "ZFA" },
                        new { Id = "178", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F572", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0072", Matcher = "ZFF" },
                        new { Id = "179", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F572", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0073", Matcher = "ZHW" },
                        new { Id = "180", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F572", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0074", Matcher = "ZLA" },
                        new { Id = "181", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0075", Matcher = "1B" },
                        new { Id = "182", CountryId = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F167", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0076", Matcher = "CL9" },
                        new { Id = "183", CountryId = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F503", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0062", Matcher = "JC1" },
                        new { Id = "184", CountryId = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F503", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0077", Matcher = "JF" },
                        new { Id = "185", CountryId = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F503", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0078", Matcher = "JY" },
                        new { Id = "186", CountryId = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F565", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0079", Matcher = "KL" },
                        new { Id = "187", CountryId = "4E8349F3-BE69-4A7E-9AC7-0188C7F3F565", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0080", Matcher = "KPT" },
                        new { Id = "188", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0056", Matcher = "4J" },
                        new { Id = "189", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0081", Matcher = "4US" },
                        new { Id = "190", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0081", Matcher = "5U" },
                        new { Id = "191", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0082", Matcher = "5X" },
                        new { Id = "192", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0056", Matcher = "55" },
                        new { Id = "193", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0040", Matcher = "93X" },
                        new { Id = "194", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0082", Matcher = "9BH" },
                        new { Id = "195", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0082", Matcher = "95P" },
                        new { Id = "196", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0081", Matcher = "98M" },
                        new { Id = "197", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0078", Matcher = "9C6" },
                        new { Id = "198", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0081", Matcher = "WBA" },
                        new { Id = "199", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0081", Matcher = "WBS" },
                        new { Id = "201", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0081", Matcher = "WBX" },
                        new { Id = "202", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F552", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0069", Matcher = "VF9" },
                        new { Id = "203", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0060", Matcher = "L2C" },
                        new { Id = "204", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0115", Matcher = "LA6" },
                        new { Id = "205", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0082", Matcher = "LBE" },
                        new { Id = "206", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F517", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0081", Matcher = "LBV" },
                        new { Id = "207", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0106", Matcher = "WEB" },
                        new { Id = "208", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0107", Matcher = "WJR" },
                        new { Id = "209", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0108", Matcher = "WMW" },
                        new { Id = "210", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0109", Matcher = "1C" },
                        new { Id = "211", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0110", Matcher = "1G3" },
                        new { Id = "212", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0111", Matcher = "1L" },
                        new { Id = "213", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0050", Matcher = "1M" },
                        new { Id = "214", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0112", Matcher = "1MR" },
                        new { Id = "215", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0050", Matcher = "4M" },
                        new { Id = "216", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0111", Matcher = "5L" },
                        new { Id = "217", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0113", Matcher = "5YJ" },
                        new { Id = "218", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0114", Matcher = "99J" },
                        new { Id = "219", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0105", Matcher = "1J" },
                        new { Id = "220", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0105", Matcher = "988" },
                        new { Id = "221", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0104", Matcher = "WKK" },
                        new { Id = "222", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0103", Matcher = "WMA" },
                        new { Id = "223", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0054", Matcher = "9BD" },
                        new { Id = "224", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0054", Matcher = "93W" },
                        new { Id = "225", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0103", Matcher = "953" },
                        new { Id = "226", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F552", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0097", Matcher = "VF4" },
                        new { Id = "227", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F552", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0097", Matcher = "VF8" },
                        new { Id = "228", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0098", Matcher = "WAG" },
                        new { Id = "229", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0099", Matcher = "WAP" },
                        new { Id = "230", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0056", Matcher = "WDB" },
                        new { Id = "231", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0029", Matcher = "WME" },
                        new { Id = "232", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0100", Matcher = "WP0" },
                        new { Id = "233", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0100", Matcher = "WP1" },
                        new { Id = "234", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0101", Matcher = "WUA" },
                        new { Id = "235", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0102", Matcher = "W09" },
                        new { Id = "236", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F552", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0059", Matcher = "VF5" },
                        new { Id = "237", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F552", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0055", Matcher = "VF6" },
                        new { Id = "238", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F552", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0096", Matcher = "VR1" },
                        new { Id = "239", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0095", Matcher = "W0L" },
                        new { Id = "240", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F557", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0095", Matcher = "W0SV" },
                        new { Id = "241", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F568", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0094", Matcher = "YS2" },
                        new { Id = "242", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F568", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0094", Matcher = "YS4" },
                        new { Id = "243", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0093", Matcher = "1G9" },
                        new { Id = "244", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0094", Matcher = "9BS" },
                        new { Id = "245", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F534", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0085", Matcher = "SAJ" },
                        new { Id = "246", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F534", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0086", Matcher = "SAL" },
                        new { Id = "247", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F534", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0087", Matcher = "SAR" },
                        new { Id = "248", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F534", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0088", Matcher = "SAT" },
                        new { Id = "249", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F534", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0089", Matcher = "SBM" },
                        new { Id = "250", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F534", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0090", Matcher = "SCC" },
                        new { Id = "251", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F534", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0091", Matcher = "SCF" },
                        new { Id = "252", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F534", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0092", Matcher = "SCE" },
                        new { Id = "253", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F568", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0042", Matcher = "YTN" },
                        new { Id = "254", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F568", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0084", Matcher = "YV1" },
                        new { Id = "255", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F568", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0084", Matcher = "YV2" },
                        new { Id = "256", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F568", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0084", Matcher = "YV3" },
                        new { Id = "257", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0083", Matcher = "4S3" },
                        new { Id = "258", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F577", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0083", Matcher = "4S4" },
                        new { Id = "259", CountryId = "4E8349F3-BE69-4A7E-9AC7-0588C7F3F598", ManufacturerId = "8b6e9487-db5b-4985-9852-ecca594d0084", Matcher = "9BV" }
                    );
                });

            modelBuilder.Entity("CoreApp.Repositories.Payment.PaymentDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("OwnedCarId");

                    b.Property<string>("PaymentPlanId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("OwnedCarId");

                    b.HasIndex("PaymentPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CoreApp.Repositories.Payment.PaymentPlanDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<string>("Description");

                    b.Property<int>("MonthsCovered");

                    b.Property<string>("Name");

                    b.Property<bool>("Repeatable");

                    b.HasKey("Id");

                    b.ToTable("PaymentPlans");

                    b.HasData(
                        new { Id = "free trial", Amount = 0, Description = "Test out the application to see how healthy your car is before you commit", MonthsCovered = 1, Name = "Free Trial", Repeatable = false },
                        new { Id = "monthly", Amount = 100, Description = "Pay for //productname on a monthly basis", MonthsCovered = 1, Name = "Monthly Plan", Repeatable = true },
                        new { Id = "annual", Amount = 1000, Description = "Pay for //productname on a yearly basis and get two month free", MonthsCovered = 12, Name = "Annual", Repeatable = true },
                        new { Id = "lifetime", Amount = 10000, Description = "Purchase //productname for the life of the Vin, transferable", MonthsCovered = 9999, Name = "Lifetime", Repeatable = false }
                    );
                });

            modelBuilder.Entity("CoreApp.Repositories.RepeatTypeDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("RepeatTypes");

                    b.HasData(
                        new { Id = "age", Name = "Age" },
                        new { Id = "mileage", Name = "Mileage" }
                    );
                });

            modelBuilder.Entity("CoreApp.Repositories.ServiceReceiptDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("CurrentMiles");

                    b.Property<string>("ServiceReminderId");

                    b.HasKey("Id");

                    b.HasIndex("ServiceReminderId");

                    b.ToTable("ServiceReceipts");
                });

            modelBuilder.Entity("CoreApp.Repositories.ServiceReminderDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("OwnedCarId");

                    b.Property<string>("RepeatingFigure");

                    b.Property<string>("RepeatingTypeId");

                    b.Property<string>("ServiceTypeId");

                    b.HasKey("Id");

                    b.HasIndex("OwnedCarId");

                    b.HasIndex("RepeatingTypeId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("ServiceReminders");
                });

            modelBuilder.Entity("CoreApp.Repositories.ServiceTypeDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new { Id = "oilchange", Name = "Oil Change" },
                        new { Id = "coolant", Name = "Coolant Flush" },
                        new { Id = "timing", Name = "Replace Timing Equipment" },
                        new { Id = "brakes", Name = "Check Brakes Depth" }
                    );
                });

            modelBuilder.Entity("CoreApp.Models.Repositories.Vehicle.CarDto", b =>
                {
                    b.HasOne("CoreApp.Models.Repositories.Vehicle.ManufacturerDto", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");
                });

            modelBuilder.Entity("CoreApp.Models.Repositories.Vehicle.MileageRecordingDto", b =>
                {
                    b.HasOne("CoreApp.Models.Repositories.Vehicle.OwnedCarDto", "OwnedCar")
                        .WithMany("MileageRecordings")
                        .HasForeignKey("OwnedCarId");
                });

            modelBuilder.Entity("CoreApp.Models.Repositories.Vehicle.OwnedCarDto", b =>
                {
                    b.HasOne("CoreApp.Models.Repositories.Vehicle.CarDto", "BaseModel")
                        .WithMany()
                        .HasForeignKey("CarId");

                    b.HasOne("CoreApp.Models.Repositories.UserDto", "Owner")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("CoreApp.Models.Repositories.Vehicle.VinWMI", b =>
                {
                    b.HasOne("CoreApp.Models.Repositories.CountryDto", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("CoreApp.Models.Repositories.Vehicle.ManufacturerDto", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");
                });

            modelBuilder.Entity("CoreApp.Repositories.Payment.PaymentDto", b =>
                {
                    b.HasOne("CoreApp.Models.Repositories.Vehicle.OwnedCarDto", "OwnedCar")
                        .WithMany()
                        .HasForeignKey("OwnedCarId");

                    b.HasOne("CoreApp.Repositories.Payment.PaymentPlanDto", "PaymentPlan")
                        .WithMany()
                        .HasForeignKey("PaymentPlanId");

                    b.HasOne("CoreApp.Models.Repositories.UserDto", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("CoreApp.Repositories.ServiceReceiptDto", b =>
                {
                    b.HasOne("CoreApp.Repositories.ServiceReminderDto", "ServiceReminder")
                        .WithMany("Receipts")
                        .HasForeignKey("ServiceReminderId");
                });

            modelBuilder.Entity("CoreApp.Repositories.ServiceReminderDto", b =>
                {
                    b.HasOne("CoreApp.Models.Repositories.Vehicle.OwnedCarDto", "OwnedCar")
                        .WithMany("ServiceReminders")
                        .HasForeignKey("OwnedCarId");

                    b.HasOne("CoreApp.Repositories.RepeatTypeDto", "RepeatingType")
                        .WithMany()
                        .HasForeignKey("RepeatingTypeId");

                    b.HasOne("CoreApp.Repositories.ServiceTypeDto", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
