version: 0.2

phases:
    install:
        commands:
            - dotnet restore
            - dotnet tool install -g Amazon.Lambda.Tools
    build:
        commands:
            - dotnet lambda package-ci -pl CoreApp --output-template template.yml --configuration release
            - aws cloudformation package --template-file template.yml --s3-bucket a----a --output-template-file serverless.yml
    post_build:
        commands:
            # Start the RDS server and update it
            #- aws rds start-db-cluster --db-cluster-identifier mechie-db-cluster
            #- aws rds wait db-instance-available --db-instance-identifier mechie-db
            #- dotnet ef database update --startup-project CoreApp --project CoreApp
            ##- aws rds stop-db-cluster --db-cluster-identifier mechie-db-cluster
      
artifacts:
    files:
        - serverless.yml
        - CoreApp/buildparams.json
    discard-paths: yes
