version: 0.2

phases:
    install:
        commands:
            - dotnet restore
            - dotnet tool install -g Amazon.Lambda.Tools
    build:
        commands:
            - dotnet publish -c release
            - dotnet lambda package-ci -pl CoreApp.Serverless
            - aws cloudformation package --template-file serverless.template --s3-bucket a----a --output-template-file serverless.yml
    post_build:
        commands:
            - 
      
artifacts:
    files:
        - serverless.yml
        - CoreApp.Serverless/buildparams.json
    discard-paths: yes
