version: 0.2

phases:
    install:
        commands:
            - dotnet restore
    build:
        commands:
            - dotnet build
            - dir
            - cd CoreApp.Serverless/obj/Debug/netcoreapp2.1/
            - dir

            
    #post_build:
    #    commands:
    #        - aws cloudformation package --template-file serverless.template --s3-bucket a----a

artifacts:
    files:
        CoreApp.Serverless/obj/Debug/netcoreapp2.1/*
    discard-paths: yes
