version: 0.2

phases:
    install:
        commands:
            - dotnet restore
    build:
        commands:
            - dotnet publish -c release
            - aws cloudformation package --template-file CoreApp.Serverless/serverless.template --s3-bucket a----a --output-template-file serverless.yml
    post_build:
        commands:
            - 
      
artifacts:
    files:
        - serverless.yml
        - CoreApp.Serverless/buildparams.json
    discard-paths: yes
