version: 0.2

phases:
    install:
        commands:
            - dotnet restore
    build:
        commands:
            - dotnet publish
            - aws cloudformation package --template-file CoreApp.Serverless/serverless.template --s3-bucket a----a --output-template-file serverless.yml

artifacts:
    files:
        serverless.yml
    discard-paths: yes
